### ISSUE TITLE
Head tittles for every page

### ISSUE THREAD

**Issue by Jaideep-C** [Jaideep-C/slop-frontend#1]
**Is your feature request related to a problem? Please describe.**
As of now when we open a new page from our project the default title is given to the page i.e the route of the page. we need to give relevant titles for every page.

**Describe the solution you'd like**
We can use next/Head to add custom titles to every page [docs](https://nextjs.org/docs/messages/no-title-in-document-head)

**Comment by racharahul** [comment]
I want to take up this task
